let response = [];

response.RESPONSE = {

  VALID_USER: { responseCode: 1, responseMessage: "" },
  SUCCESS: { responseCode: 200, responseMessage: "Success" },
  INVALID_USER: { responseCode: 201, responseMessage: "User does not exist" },
  INVALID_ACCESS_TOKEN: { responseCode: 202, responseMessage: "Invalid Access Token" },
  PARAMETER_IS_MANDATORY: { responseCode: 203, responseMessage: "paramName is Mandatory Parameter" },
  INVALID_DATA: { responseCode: 204, responseMessage: "Invalid input Data. Input parameters sent are invalid" },
  INVALID_ACTION: { responseCode: 205, responseMessage: "Invalid action" },
  METHOD_NOT_FOUND: { responseCode: 206, responseMessage: "API does not exist" },
  INVALID_REQUEST_METHOD: { responseCode: 207, responseMessage: "The request method for the API is invalid" },
  RESPONSE_CODE_NOT_FOUND: { responseCode: 208, responseMessage: "Response code not found" },
  INVALID_INPUT_INTEGER: { responseCode: 209, responseMessage: "paramName should be a integer" },
  INVALID_INPUT_STRING: { responseCode: 210, responseMessage: "paramName should be a string" },
  INVALID_BOOLEAN_INPUT: { responseCode: 211, responseMessage: "paramName should be a boolean" },
  INVALID_INPUT_EMPTY: { responseCode: 212, responseMessage: "paramName should not be empty" },

  INVALID_FACEBOOK_ACCESS_TOKEN: { responseCode: 213, responseMessage: "Facebook access token is Invalid" },
  USER_IS_BANNED: { responseCode: 214, responseMessage: "User is banned" },
  INVALID_PASSWORD: { responseCode: 215, responseMessage: "Invalid Password" },
  VERIFICATION_EMAIL_SENT: { responseCode: 216, responseMessage: "Verification mail has been sent" },
  EMAIL_ALREADY_EXISTS: { responseCode: 217, responseMessage: "Cannot sign up! The given email already exists" },
  INVALID_EMAIL: { responseCode: 218, responseMessage: "Email is Invalid" },
  INVALID_FEEDBACK_MESSAGE: { responseCode: 219, responseMessage: "The feedback sent is invalid/exceeds max size" },
  EMAIL_VERIFICATION_PENDING: { responseCode: 220, responseMessage: "Email has already been sent and is pending to be verified" },
  EMAIL_VERIFICATION_SENT: { responseCode: 221, responseMessage: "Verification email sent" },
  INVALID_PURCHASE: { responseCode: 222, responseMessage: "Cannot purchase! Invalid id provided" },
  EVENT_ALREADY_JOINED: { responseCode: 223, responseMessage: "Cannot join! User has already joined this event" },
  INVALID_EVENT: { responseCode: 224, responseMessage: "The event is invalid" },
  EVENT_NOT_ACTIVE: { responseCode: 225, responseMessage: "The event you are trying to join is not active now" },
  USER_ALREADY_LOGGED_IN_OTHER_DEVICE: { responseCode: 226, responseMessage: "User is already logged in other device. Use force login to continue" },
  USERNAME_UPDATE_REQUIRED: { responseCode: 227, responseMessage: "The email logged in user has no username. Update the username" },
  INVALID_MATCH_DATA: { responseCode: 228, responseMessage: "The match data sent is invalid " },
  ITEM_ALREADY_PURCHASED: { responseCode: 229, responseMessage: "The Item is already purchased" },
  INSUFFICIENT_COINS: { responseCode: 230, responseMessage: "You don't have enough coins to perform this action" },
  UNKNOWN_ERROR: { responseCode: 231, responseMessage: "Error" },
  INVALID_ROOM: { responseCode: 232, responseMessage: "Invalid Room" },
  INVALID_OPPONENT_USER: { responseCode: 233, responseMessage: "Invalid Opponent user id" },
  DATA_CONFLICT: { responseCode: 234, responseMessage: "Use force link! Choose either device data or server data to proceed" },
  INSUFFICIENT_CRYSTALS: { responseCode: 235, responseMessage: "You don't have enough cystals to perform this action" },
  PLAYER_ALREADY_IN_ROOM: { responseCode: 236, responseMessage: "Player has already joined the room" },
  INVALID_USERNAME: { responseCode: 237, responseMessage: "The username is invalid" },
  EMAIL_VERIFIED: { responseCode: 238, responseMessage: "Email is verified" },
  INVALID_EMAIL_VERIFICATION: { responseCode: 239, responseMessage: "Email is already verified" },
  DAILY_REWARD_ALREADY_COLLECTED: { responseCode: 240, responseMessage: "The daily reward is already collected" },
  SHOP_FREE_COINS_REWARD_ALREADY_COLLECTED: { responseCode: 241, responseMessage: "All shop free coins rewards already collected" },
  NEXT_SHOP_FREE_COINS_REWARD_UNAVAILABLE: { responseCode: 242, responseMessage: "Next shop free coins reward currently unavailable" },
  INVALID_EVENT_OBJECTIVE: { responseCode: 243, responseMessage: "The event objective data is invalid" },
  INVALID_EVENT_REWARDS: { responseCode: 244, responseMessage: "The event rewards data is invalid" },
  INVALID_EVENT_TIME: { responseCode: 245, responseMessage: "The event start and end time is invalid" },
  EVENT_NOT_OVER: { responseCode: 246, responseMessage: "The event is not yet over" },
  USER_PARTICIPATION_NOT_FOUND: { responseCode: 247, responseMessage: "User has not participated in the event" },
  USER_NOT_REWARDED: { responseCode: 248, responseMessage: "User has not been rewarded for the event" },
  EVENT_REWARD_ALREADY_CLAIMED: { responseCode: 249, responseMessage: "The event reward has already been claimed" },
  ADMIN_USERNAME_ALREADY_EXISTS: { responseCode: 250, responseMessage: "The admin username already exists" },
  INVALID_ADMIN: { responseCode: 251, responseMessage: "Admin is invalid" },
  EVENT_NOT_STARTED: { responseCode: 252, responseMessage: "The event is not yet started" },
  INVALID_LEADERBOARD: { responseCode: 253, responseMessage: "Leaderboard cannot be viewed" },
  USER_ALREADY_IN_AN_EVENT: { responseCode: 254, responseMessage: "User is already in an event" },
  INVALID_PLAYER_USERID: { responseCode: 255, responseMessage: "Invalid player user id" },
  USER_ALREADY_REWARDED: { responseCode: 256, responseMessage: "User has already been rewarded" },
  REWARD_NOT_FOUND: { responseCode: 257, responseMessage: "No reward found" },
  INVALID_UPI_DATA: { responseCode: 258, responseMessage: "The upi data is invalid" },
  REWARD_NOT_CLAIMED: { responseCode: 259, responseMessage: "The reward has not been claimed" },
  UPI_DATA_NOT_FOUND: { responseCode: 260, responseMessage: "Upi data not found" }
}

module.exports = response;
